### ISSUE TITLE
[Feature Request] Allow configuration of CPU throttle & networkConditions

### ISSUE THREAD

**Issue by rondale-sc** [krisselden/ember-macro-benchmark#17]
I think it'd be cool if we made it easy to set these to better gauge performance differences on mobile

I think it'd be just a matter of allowing these props to be sent from the server config block.

```
  cpuThrottleRate: 1,
  networkConditions: {
    offline: false,
    latency: 0,
    downloadThroughput: 0,
    uploadThroughput: 0
  },
```

I'm not sure what unit `downloadThroughput` and `uploadThroughput` should be in though.  

https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-emulateNetworkConditions

Just says that they both need to be numbers.

**Comment by krisselden** [comment]
Depends on what you are trying to simulate, you can look up what they are typically for various regions and networks.

https://www.npmjs.com/package/network-emulation-conditions
